"""add homework table

Revision ID: 055df61025b1
Revises: a240d147ba72
Create Date: 2026-09-16 23:37:23.755857

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '055df61025b1'
down_revision: str | Sequence[str] | None = 'a240d147ba72'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('disciplines', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('code_url', sa.Text(), nullable=True),
    sa.Column('live_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', name='homework_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homework')
    # ### end Alembic commands ###
