"""store uploaded source bytes in postgres

Revision ID: 07e0d73d15ff
Revises: 4989a81487f5
Create Date: 2026-09-17 01:49:29.047126

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '07e0d73d15ff'
down_revision: str | Sequence[str] | None = '4989a81487f5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    op.add_column('source', sa.Column('file_media_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'file_media_type')
    op.drop_column('source', 'file_data')
    # ### end Alembic commands ###
