"""add quiz attempt

Revision ID: 32153d0a3fa9
Revises: be9418e394b2
Create Date: 2026-09-16 23:48:14.756172

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '32153d0a3fa9'
down_revision: str | Sequence[str] | None = 'be9418e394b2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_attempt',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('item_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', name='quiz_attempt_status'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempt_user_id'), 'quiz_attempt', ['user_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempt_week'), 'quiz_attempt', ['week'], unique=False)
    op.add_column('attempt', sa.Column('quiz_attempt_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_attempt_quiz_attempt_id'), 'attempt', ['quiz_attempt_id'], unique=False)
    op.create_foreign_key(None, 'attempt', 'quiz_attempt', ['quiz_attempt_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attempt', type_='foreignkey')
    op.drop_index(op.f('ix_attempt_quiz_attempt_id'), table_name='attempt')
    op.drop_column('attempt', 'quiz_attempt_id')
    op.drop_index(op.f('ix_quiz_attempt_week'), table_name='quiz_attempt')
    op.drop_index(op.f('ix_quiz_attempt_user_id'), table_name='quiz_attempt')
    op.drop_table('quiz_attempt')
    # ### end Alembic commands ###
