"""add attempt table

Revision ID: 40815078ac61
Revises: 451406f2da45
Create Date: 2026-09-12 11:41:00.446339

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '40815078ac61'
down_revision: str | Sequence[str] | None = '451406f2da45'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempt',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('response_hash', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rubric_hits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('misconceptions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('feedback_md', sa.Text(), nullable=False),
    sa.Column('grader_model', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempt_item_id'), 'attempt', ['item_id'], unique=False)
    op.create_index(op.f('ix_attempt_response_hash'), 'attempt', ['response_hash'], unique=False)
    op.create_index(op.f('ix_attempt_user_id'), 'attempt', ['user_id'], unique=False)
    # NOTE: autogenerate wants to drop `chunk.embedding` here because that column is raw DDL
    # (see the M2 migration), not a mapped SQLAlchemy column — same reason as in the M3
    # migration. Left alone on purpose; unrelated to this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempt_user_id'), table_name='attempt')
    op.drop_index(op.f('ix_attempt_response_hash'), table_name='attempt')
    op.drop_index(op.f('ix_attempt_item_id'), table_name='attempt')
    op.drop_table('attempt')
    # ### end Alembic commands ###
