"""note body optional, add url

Revision ID: 4989a81487f5
Revises: 32153d0a3fa9
Create Date: 2026-09-17 00:39:15.534992

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4989a81487f5'
down_revision: str | Sequence[str] | None = '32153d0a3fa9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('url', sa.Text(), nullable=True))
    op.alter_column('note', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('note', 'url')
    # ### end Alembic commands ###
