"""add user, source, chunk, ingest_job

Revision ID: 4f556fc29e38
Revises: 
Create Date: 2026-09-11 19:59:31.607663

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4f556fc29e38'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'student', 'demo', name='user_role'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('source',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('lecture_pdf', 'slides', 'transcript', 'paper', 'notes', name='source_kind'), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'ingested', 'failed', name='source_status'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_sha256'), 'source', ['sha256'], unique=True)
    op.create_table('chunk',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('locators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'ordinal', name='uq_chunk_source_ordinal')
    )
    op.create_index(op.f('ix_chunk_source_id'), 'chunk', ['source_id'], unique=False)
    # pgvector column: no `pgvector` Python dependency yet (nothing writes embeddings
    # until M3/M7), so this is raw DDL rather than a mapped SQLAlchemy column.
    op.execute("ALTER TABLE chunk ADD COLUMN embedding vector(1536)")
    op.create_table('ingest_job',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('parse_and_chunk', name='ingest_job_kind'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='ingest_job_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_job_source_id'), 'ingest_job', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingest_job_source_id'), table_name='ingest_job')
    op.drop_table('ingest_job')
    op.drop_index(op.f('ix_chunk_source_id'), table_name='chunk')
    op.execute("ALTER TABLE chunk DROP COLUMN embedding")
    op.drop_table('chunk')
    op.drop_index(op.f('ix_source_sha256'), table_name='source')
    op.drop_table('source')
    op.drop_table('user')
    # ### end Alembic commands ###
