"""add item table

Revision ID: 8cef87849693
Revises: 4f556fc29e38
Create Date: 2026-09-12 08:29:12.330458

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8cef87849693'
down_revision: str | Sequence[str] | None = '4f556fc29e38'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('chunk_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('type', sa.Enum('free_recall', 'term_def', 'cloze', 'mcq', 'compare', 'application', name='item_type'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('reference_answer', sa.Text(), nullable=False),
    sa.Column('rubric', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('choices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('bloom', sa.Enum('recall', 'understand', 'apply', 'analyze', name='item_bloom'), nullable=False),
    sa.Column('topics', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'edited', 'retired', name='item_status'), nullable=False),
    sa.Column('gen_model', sa.String(), nullable=False),
    sa.Column('gen_prompt_version', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_source_id'), 'item', ['source_id'], unique=False)
    # NOTE: autogenerate wants to drop `chunk.embedding` here because that column is raw DDL
    # (see the M2 migration), not a mapped SQLAlchemy column — same reason as there. Left
    # alone on purpose; unrelated to this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_source_id'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
