"""add tokens_used to attempt

Revision ID: a240d147ba72
Revises: 40815078ac61
Create Date: 2026-09-16 22:59:09.827342

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a240d147ba72'
down_revision: str | Sequence[str] | None = '40815078ac61'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Backfill existing rows with 0 (their real cost predates budget tracking, and 0 never
    # falsely trips the daily cap), then drop the default — every row written by the app
    # from here on sets tokens_used explicitly, same as latency_ms.
    op.add_column(
        'attempt', sa.Column('tokens_used', sa.Integer(), nullable=False, server_default='0')
    )
    op.alter_column('attempt', 'tokens_used', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempt', 'tokens_used')
    # ### end Alembic commands ###
