"""add review_state table

Revision ID: f1da6e62b4db
Revises: 07e0d73d15ff
Create Date: 2026-09-22 21:41:12.585696

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f1da6e62b4db'
down_revision: str | Sequence[str] | None = '07e0d73d15ff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_state',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('last_grade', sa.String(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fsrs_card', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', name='uq_review_state_user_item')
    )
    op.create_index(op.f('ix_review_state_due_at'), 'review_state', ['due_at'], unique=False)
    op.create_index(op.f('ix_review_state_item_id'), 'review_state', ['item_id'], unique=False)
    op.create_index(op.f('ix_review_state_user_id'), 'review_state', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_state_user_id'), table_name='review_state')
    op.drop_index(op.f('ix_review_state_item_id'), table_name='review_state')
    op.drop_index(op.f('ix_review_state_due_at'), table_name='review_state')
    op.drop_table('review_state')
    # ### end Alembic commands ###
